### PR TITLE
Add GTK 4 Demo and Flatpak manifest

### LINKED ISSUE #2: Merging changes from mjakeman/lasem
Hi,

I've been maintaining my own fork of Lasem under the assumption that upstream development had stopped (see: https://github.com/mjakeman/lasem/issues/23).

It has a few additional features/changes on top of this repo:
 * An independent port to meson (not as robust as the one here)
 * CI Pipeline
 * Demo application integrating lasem into gtk4
 * Flatpak manifest for one-click building the demo with gnome-builder
 * Documentation using gi-docgen (hosted at https://www.mattjakeman.com/lasem)

Would you be open to integrating some of the above changes? I'd like to discontinue my fork and converge around this one if you are agreeable.

Thanks! :)

### PR DESCRIPTION
**Pull request by mjakeman**
Changes:
 - Adds a GTK 4 demo for integrating Lasem into an application
 - Adds flatpak manifest for the demo
 - Adds 'demo' build option

This is ported over mostly as-is from my fork.

I've included a flatpak manifest for building and running the demo. This is incredibly useful for working on the library with GNOME Builder as it doesn't require any dependencies to be installed on the host system.

There are a few points I'm not sure about:
 - [x] App ID for the demo. I've gone with `io.github.LasemProject.LasemDemo` but this can be anything really
 - [x] Copyright notice on the file. I was going to add LGPL but does that make sense for the demo code?

Happy to change as needed

Fixes #2

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Hi Matt,

Thanks for the merge request.

Do you have future plan about this demo ? Will it still be just a sample software, or will it evolve to a viewer ?

**Comment by mjakeman** [comment]
I'm happy to take it in any direction. At the moment, the demo is mainly a way to work on Lasem more easily, but it wouldn't take too much effort to make it into a `.mathml`/`.svg` viewer.

My interest in Lasem is to make an equation editor which can be embedded into other applications (e.g. inline equation editing inside a text document). This would be a standalone application, but perhaps a subset of it could be suitable as a demo for usage of this library.

**Comment by EmmanuelP** [comment]
> I'm happy to take it in any direction. At the moment, the demo is mainly a way to work on Lasem more easily, but it wouldn't take too much effort to make it into a `.mathml`/`.svg` viewer.
> 
> My interest in Lasem is to make an equation editor which can be embedded into other applications (e.g. inline equation editing inside a text document). This would be a standalone application, but perhaps a subset of it could be suitable as a demo for usage of this library.

Ok. So could you rename the demo to viewer, and make it load a file instead of displaying what is inline ?

**Comment by EmmanuelP** [comment]
> App ID for the demo. I've gone with `io.github.LasemProject.LasemDemo` but this can be anything really

I would go for org.lasem.Viewer

**Comment by EmmanuelP** [comment]
> Copyright notice on the file. I was going to add LGPL but does that make sense for the demo code?

If at some point part of the code could go into a library (an equation editor GUI for example), I prefer to keep LGPL for now.

**Comment by EmmanuelP** [comment]
Thanks a lot

**Pull request merged**
